# Generated by Django 5.2.5 on 2025-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="github_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
