# Generated by Django 5.2.5 on 2025-08-24 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DecorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="image_name",
                        max_length=100,
                        verbose_name="Читаемый идентификатор",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="decor/",
                        verbose_name="Фотография",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("bio", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="master/", verbose_name="Фотография"
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        help_text="Опыт работы в годах", verbose_name="Стаж работы"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Время выполнения в минутах",
                        verbose_name="Длительность",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, verbose_name="Популярная услуга"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="service/", verbose_name="Изображение"
                    ),
                ),
                (
                    "masters_who_provides",
                    models.ManyToManyField(to="core.master", verbose_name="Мастера"),
                ),
            ],
            options={
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.master",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "services_were_provided",
                    models.ManyToManyField(
                        to="core.service", verbose_name="Оказанные услуги"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "новая"),
                            ("confirmed", "подтвержденная"),
                            ("cancelled", "отмененная"),
                            ("completed", "выполненная"),
                        ],
                        default="new",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Назначенные дата и время"
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.master",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(to="core.service", verbose_name="Услуги"),
                ),
            ],
            options={
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AddField(
            model_name="master",
            name="services_provided",
            field=models.ManyToManyField(to="core.service", verbose_name="Услуги"),
        ),
    ]
